version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.15.0
    steps:
      - restore_cache:
          keys:
            - git-lfs-install
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install Git LFS and pull files
          command: |
            if ! [ -f /tmp/git-lfs.tar.gz ]; then
                curl -L -o /tmp/git-lfs.tar.gz \
                  https://github.com/git-lfs/git-lfs/releases/download/v2.7.1/git-lfs-linux-amd64-v2.7.1.tar.gz
            fi
            tar xf /tmp/git-lfs.tar.gz -C /tmp
            sudo /tmp/install.sh
            git lfs update --force
            git lfs install
            git lfs pull
      - save_cache:
          key: git-lfs-install
          paths:
            - /tmp/git-lfs.tar.gz
      - checkout
      - run:
          name: Install NPM modules
          command: |
            yarn cache dir
            yarn install --frozen-lockfile
            yarn add firebase-tools
            yarn run firebase --version
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Deploy
          command: |
            yarn deploy
